config/routes.rb
Site2025::Application.routes.draw do
  get "resources/web_resources"
  get "resources/toys_and_games"
  get "resources/camps_and_events"
  get "resources/awards_scholarships"
  get "resources/books"
  get "resources/add"
  resources :articles
  resources :resource_types
  get "articles/index"
 
  root 'static_pages#home'

   match '/contact', to: 'static_pages#contact', via: 'get'
   match '/about_us', to: 'static_pages#about_us', via: 'get'
   match '/get_started', to: 'static_pages#get_started', via: 'get'
   match '/getstarted2', to: 'static_pages#getstarted2', via: 'get'
   match '/blog', to: 'static_pages#blog', via: 'get'
   match '/services', to: 'static_pages#services', via: 'get'
    
   match '/intro_to_engineering', to: 'static_pages#intro_to_engineering', via: 'get'
   match '/engineering_process', to: 'static_pages#engineering_process', via: 'get'
   match '/structures', to: 'static_pages#structures', via: 'get'
   match '/materials', to: 'static_pages#materials', via: 'get'
   match '/machines', to: 'static_pages#machines', via: 'get' 
   match '/energy', to: 'static_pages#energy', via: 'get'
   match '/computing', to: 'static_pages#computing', via: 'get'
   
   match '/research', to: 'articles#index', via: 'get'
   match '/dashboard', to: 'articles#dashboard', via: 'get'
   match '/rdashboard', to: 'articles#rdashboard', via: 'get'
   match '/new', to: 'articles#new', via: 'get'
   match '/resources', to: 'resource_types#index', via: 'get'
   match '/web_resources', to: 'resource_types#web_resources', via: 'get'
   match '/parents_home', to: 'static_pages#parents_home', via: 'get'
   
   
    

  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :resource_type
  
end

app/models/resource_type.rb
class ResourceType < ActiveRecord::Base
  has_many :resources
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end

  def index
    @articles = Article.all
  end
  
  def dashboard
  end
  
  

end

app/controllers/resource_types_controller.rb
class ResourceTypesController < ApplicationController
  
  def new
  end

  def index
    @resource_types = ResourceType.all
  end
  
  def web_resources
    @resource_type = ResourceType.where(r_type: "Web Resources")
    @resources = Resource.where(r_type: "Web Resources")
  end
  
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  
  def web_resources
    @resource_type = ResourceType.where(r_type: "Web Resources")
    @resources = Resource.where(r_type: "Web Resources")
    
  end

  def toys_and_games
    @resource_type = ResourceType.where(r_type: "Toys and Games")
    @resources = Resource.where(r_type: "Toys and Games")
  end

  def camps_and_events
    @resource_type = ResourceType.where(r_type: "Camps and Events")
    @resources = Resource.where(r_type: "Camps and Events")
  end

  def awards_scholarships
    @resource_type = ResourceType.where(r_type: "Awards and Scholarships")
    @resources = Resource.where(r_type: "Awards and Scholarships")
  end

  def books
     @resource_type = ResourceType.where(r_type: "Books")
     @resources = Resource.where(r_type: "Books")
   end


  def add
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about_us
  end

  def contact
  end
  
  def get_started
  end

  def getstarted2
  end
  
  def intro_to_engineering
  end
  
  def engineering_process
  end

  def kids_site
  end
    
  def structures
  end
  
  def materials
  end
  
  def machines
  end
  
  def energy
  end
  
  def computing
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Engineering for Kids"
    if page_title.empty?
      base_title
    else
      page_title
    end
  end  
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/resource_types_helper.rb
module ResourceTypesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html-bak.erb
<div class="container-fluid" style="padding-left: 30px; padding-right: 30px; padding-top: 0px;">

	<div class="footer" >
		<div class="row featurette" >
			<div class="slidearea-footer">
				<div class="col-sm-3" style="text-align:left">
					 <%= link_to image_tag("2025_logo.png", :alt => "2025Labs Logo"),   root_path %>
					 <br>
					 <span class="muted">Copyright &copy;, 2016 - 2025 Labs LLC</span>
				</div> <!--col-sm-3-->


				<div class="col-sm-3" style="text-align:left">
					<a class="footheader" <%= link_to "Home",    root_path %></a><br>
					<a class="footsub" <%= link_to "2025 Labs",    root_path %></a><br>
					<a class="footsub" href="http://www.2025consulting.com" target="_blank">2025 Consulting</a><br>
					<a class="footsub" href="http://www.2025kids.com" target="_blank">2025 Kids Site</a><br>
					<a class="footsub" <%= link_to "About Us",    about_us_path %></a><br>
<!--					<a class="footsub" <%= link_to "Contact",    contact_path %></a><br> -->
<!--					<a class="footsub" <%= link_to "Blog",    blog_path %></a>		-->
				</div>	<!--col-sm-3-->


				<div class="col-sm-3" style="text-align:left">
					<a class="footheader" <%= link_to "Resources",    resources_path %></a><br>
					<a class="footsub" <%= link_to "Web Resources",    resources_web_resources_path, html_options = {:alt=>"Engineering for Kids Web Resources"}  %></a><br>
					<a class="footsub" <%= link_to "Toys and Games",    resources_toys_and_games_path, html_options = {:alt=>"Engineering Toys and Games"}  %></a><br>
					<a class="footsub" <%= link_to "Camps and Events",    resources_camps_and_events_path, html_options = {:alt=>"Engineering Camps and Events"}  %></a><br>
					<a class="footsub" <%= link_to "Awards and Scholarships",    resources_awards_scholarships_path, html_options = {:alt=>"Engineering and Computer Science Scholarships"}  %></a><br>
					<a class="footsub" <%= link_to "Books",    resources_books_path, html_options = {:alt=>"Engineering for Kids Books"}  %></a>
				</div><!--col-sm-3-->

				<div class="col-sm-3" style="text-align:left">
					<a class="footheader" <%= link_to "Research",    research_path %></a><br>
					<a class="footsub" <%= link_to "Research Articles",    research_path %></a><br>
					<a class="footsub" <%= link_to "Dashboard",    dashboard_path, html_options = {:alt=>"Dashboards tracking Equity in Engineering"}  %></a>
				</div><!--col-sm-3-->
			</div><!--row-->
			</div>
		</div> <!--container-->
</div> <!--footer-->

app/views/layouts/_header.html.erb
<div class="container-banner">
 <div class="row", style= "padding-top:10px;">			
	<div class="logo_mainbkgd">
			<span class="banner-top-2025"> Welcome to 2025 Labs</span>
	</div> <!-- background -->
</div>	
</div>

<div class="container-header">
<div class="navbar navbar-2025">	<!--nav class starts here-->
	<div class = "container-fluid" > <!--container-fluid -->

		<div class="navbar-header"> 
			<%= link_to image_tag("2025_labs_no-tagline_300x100.png", 
			:class=> 'navbar-brand'), root_path %>
			<button type="button" class="navbar-toggle collapsed" data-toggle	="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded ="false">
				<span class="sr-only"> Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

			<ul class="nav navbar-nav navbar-right">

				<li class="<%= 'active' if current_page?(root_path) %>">
					<%= link_to "Home", root_path %> 
				</li>
				
				<li><a href="http://www.2025kids.com" target="_blank">Kids Site</a>
				</li>

				<li class="dropdown">
					<a href="#"  class="dropdown-toggle" data-toggle="dropdown">Resources<b class="caret"></b>
					</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Web Resources",   resources_web_resources_path, html_options = {:alt=>"Engineering for Kids Web Resources"}  %>
							</li>
							<li><%= link_to "Toys and Games",    resources_toys_and_games_path, html_options = {:alt=>"Engineering for Kids Toys and Games"}  %>
							</li>
							<li><%= link_to "Camps and Events",    resources_camps_and_events_path, html_options = {:alt=>"Engineering for Kids Camps and Events"}  %>
							</li>
							<li><%= link_to "Scholarships",    resources_awards_scholarships_path, html_options = {:alt=>"Engineering for Kids Scholarships"}  %>
							</li>
							<li><%= link_to "Books",    resources_books_path, html_options = {:alt=>"Engineering for Kids Books"}  %>
							</li>
						</ul>
				</li>

				<li class="dropdown">
						<a href="#"  class="dropdown-toggle" data-toggle="dropdown">Research<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%=link_to "Research Articles", research_path%>
							</li>
							<li><%=link_to "Dashboard", dashboard_path%>
							</li>
						</ul>
				</li>
				
				<!-- <li class="dropdown"> -->
						<!-- <a href="#"  class="dropdown-toggle" data-toggle="dropdown">About<b class="caret"></b></a> -->
						<!-- <ul class="dropdown-menu"> -->
							<!-- <li><%=link_to "About Us", about_us_path%> -->
							<!-- </li> -->
							<!-- <li><%=link_to "Contact", contact_path%> -->
							<!-- </li> -->
							<!-- <li><%=link_to "Blog", blog_path%> -->
							<!-- </li> -->
						<!-- </ul> dropdown menu  -->
					<!-- </li> dropdown -->


			</ul> <!--nav navbar-nav navbar-right -->
		</div> <!-- navbar-collapse-->
	</div> <!--container-fluid -->
</div> <!--nav -->
</div>




					

app/views/resources/books.html.erb
<div class="container-fluid">
<div class="slidearea" style="padding-bottom: 20px; padding-left: 10px; padding-right: 10px;">
<% provide(:title, 'Engineering Books for Kids: 2025 Labs') %>
<% provide(:description, 'A list of some really great books to help introduce kids to Engineering. Some are written for the kids themselves; a few might be better read by the parents first.') %>

<div class="row featurette grid-divider">
	<div class="col-sm-2">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12">
				<span class="visible-sm visible-md visible-lg">
					<%= render "static_pages/resourcesnav" %>
					</span>
				</div>
			</div>
		</div>
	</div>

	<div class="col-sm-7">
		<div class="col-padding1">
		<h2> Engineering Books and Magazines for Kids </h2>
		This page includes some books that we have taken a look at and have decided are a good resource to introduce Engineering to kids. The books listed are coded according to the engineering area(s) that the resource pertains to, such as the Engineering Process, Machines, Energy, or Computing. 
		<p><p>We've included links to shop for these books online. We like Amazon for the reviews, because parents share their experiences in great detail. Besides, we do earn a tiny little bit of money for any sales that occur through this channel, which will help us fund more of this research and content! You can also take a look at your local public library. If they don't have it in stock in your local branch, they can often find a way to locate them elsewhere and provide them to you.<br><br>
	
		<% @resources.each do |resource| %>
	<div class="row featurette">
			<div class="col-sm-2">
		<br> 
					<% unless resource.engineering_process.blank? %>
						<%= link_to image_tag(resource.engineering_process, :class => 'resourcebutton'),   engineering_process_path %>
					<% end %>		
					
					<% unless resource.materials.blank? %>
						<%= link_to image_tag(resource.materials, :class => 'resourcebutton'),   materials_path %>
					<% end %>
					
					<% unless resource.structures.blank? %>
						<%= link_to image_tag(resource.structures, :class => 'resourcebutton'),   structures_path %>
					<% end %>
					
					<% unless resource.machines.blank? %>
						<%= link_to image_tag(resource.machines, :class => 'resourcebutton'),   machines_path %>
					<% end %>

					<% unless resource.energy.blank? %>
						<%= link_to image_tag(resource.energy, :class => 'resourcebutton'),   energy_path %>
					<% end %>

					<% unless resource.computing.blank? %>
						<%= link_to image_tag(resource.computing, :class => 'resourcebutton'),   computing_path %>
					<% end %>
				<p><%= resource.ages %>	 
			</div>
		
			<div class="col-sm-2"> <br>
				<%= resource.buy_link.html_safe %>
			</div>

			<div class="col-sm-8">
				<span class="colortxt2"><%=resource.title.html_safe %></span>
				<%=resource.description.html_safe %>			
			</div> <!--col-sm-9-->	
		</div><!--row-->	

		<div class="row">
			<div class="col-sm-12">
			</div> <!--col-sm-12-->	
		</div> <!--row-->
		<% end %> <br>
		
		<a href="mailto:info@2025labs.com?Subject=Suggestion%20For%20Web%20Resources" target="_top"><%= image_tag("pics/resource_suggestion.png", :alt => "suggest a resource", :class =>"center") %></a>
		
		<a > <img class="center" src=""> </a>
		</div>				
    </div> <!--col-sm-7-->	
    
	<div class="col-sm-3">	
		<div class="col-padding2">
		<span class="visible-sm visible-md visible-lg">
		<div class="container-fluid">
		<div class="row">
		
		
			<div class="facts2"><a class="facts1" <%= link_to "financial benefits and the ability to solve world problems",    research_path %></a></div>
			<br>
			A 2011 Intel survey highlighted that knowledge of the financial benefits and the ability to solve world problems were key influences that changed the perceptions of teens about what it means to be an Engineer and increased their interest in an Engineering career
			<hr>
    	</div> <!--col-sm-12-->
    	</div>

        <div class="row">
			<div class="col-sm-12">				
			</div> <!--col-sm-12-->
		</div> <!--row-->

		<div class="row" style="text-align:center">
			<br>
			<iframe src="http://rcm-na.amazon-adsystem.com/e/cm?t=2025labs-20&o=1&p=14&l=ur1&category=booksteach&banner=01W6KZG4QZMD00EKF982&f=ifr&linkID=QMLVNOJVRLPI7O37" width="160" height="600" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
						
		</div> <!--row-->
		</span>
		</div>
	</div> <!--col-sm-3-->	
	</div>
	</div>
</div>	<!--row-->
</div>

app/views/resources/toys_and_games.html.erb
<div class="container-fluid">
<div class="slidearea" style="padding-bottom: 20px; padding-left: 10px; padding-right: 10px;">
<% provide(:title, 'Engineering Toys and Games for Kids: 2025 Labs') %>
<% provide(:description, 'Engineering toys and games for kids that can be used to introduce kids to Engineering. Some of them are gender-neutral, and some are focused on girls specifically.') %>

<div class="row featurette grid-divider">

	<div class="col-sm-2">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12">
				<span class="visible-sm visible-md visible-lg">
					<%= render "static_pages/resourcesnav" %>
					</span>
				</div>
			</div>
		</div>
	</div>
	
    <div class="col-sm-7">
    	<div class="col-padding1">
		<% @resource_type.each do |resource_type| %>
		<h2> <%= resource_type.r_type.html_safe%> </h2>
		<%= resource_type.description.html_safe%><p><p>
		We've included links to shop for these toys online. We like Amazon for the reviews, because parents share their experiences in great detail. Besides, we do earn a tiny little bit of money for any sales that occur through this channel, which will help us fund more of this research and content! <br><br>
		
		<% end %>
		
		<% @resources.each do |resource| %>
		<div class="row">
			<div class="col-sm-2">
				<% unless resource.engineering_process.blank? %>
					<%= link_to image_tag(resource.engineering_process, :class => 'resourcebutton'),   engineering_process_path %>
				<% end %>
				
				<% unless resource.materials.blank? %>
					<%= link_to image_tag(resource.materials, :class => 'resourcebutton'),   materials_path %>
				<% end %>
				
				<% unless resource.structures.blank? %>
					<%= link_to image_tag(resource.structures, :class => 'resourcebutton'),   structures_path %>
				<% end %>
				
				<% unless resource.machines.blank? %>
					<%= link_to image_tag(resource.machines, :class => 'resourcebutton'),   machines_path %>
				<% end %>
				
				<% unless resource.energy.blank? %>
					<%= link_to image_tag(resource.energy, :class => 'resourcebutton'),   energy_path %>
				<% end %>
				
				<% unless resource.computing.blank? %>
					<%= link_to image_tag(resource.computing, :class => 'resourcebutton'),   computing_path %>
				<% end %>
				<p><%= resource.ages %>	
			</div>
			
			<div class="col-sm-10">
				<% unless resource.title.blank? %>
					<span class="colortxt2"><%=resource.title.html_safe %></span>
				<% end %>
				<%= resource.description.html_safe %>
				<p>
				<!--<% if resource.buy_link %>
					<a href= <%= resource.buy_link%> target="_blank"><%= image_tag("logos/amazon_buy.gif") %></a><%= resource.amazon_img.html_safe %> 
				<% end %>	-->	
			</div> <!--span9-->	
		</div><!--row-->	

		<div class="row">
			<div class="col-sm-12">
			</div> <!--col-sm-2-->	
		</div> <!--row-->
		<% end %>
		
		<a href="mailto:info@2025labs.com?Subject=Suggestion%20For%20Web%20Resources" target="_top"><%= image_tag("pics/resource_suggestion.png", :alt => "suggest a resource", :class =>"center") %></a>
		</div>				
    </div> <!--col-sm-7-->	
		
	<div class="col-sm-3">	
		<div class="col-padding2">
		<span class="visible-sm visible-md visible-lg">
		<div class="container-fluid">
				<div class="row">

			
			<div class="facts2"><a class="facts1" <%= link_to "financial benefits and the ability to solve world problems",    research_path %></a></div>
	
			<br>
			A 2011 Intel survey highlighted that knowledge of the financial benefits and the ability to solve world problems were key influences that changed the perceptions of teens about what it means to be an Engineer and increased their interest in an Engineering career

			
			
			<%#= link_to image_tag("facts/intelmoneymeaning.png", :alt => "Financial benefits and the ability to solve world programs are key influences in teens perceptions of engineering"),   research_path %>
			<hr>
    			</div> <!--row-->
    		</div>
        	<div class="row">
			<div class="col-sm-12">				
			</div> <!--col-sm-12-->
			</div> <!--row-->
		
			<div class="row" style="text-align:center">
			<iframe src="http://rcm-na.amazon-adsystem.com/e/cm?t=2025labs-20&o=1&p=14&l=ur1&category=stem&banner=09PFBRBM7S1P6G18CPG2&f=ifr&linkID=UPKW3XOG5NQIOX4H" width="160" height="600" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
			
			</div> <!--row-->
			</span>
	</div> <!--col-sm-3-->	
</div>
</div>		
</div>	<!--row-->
</div>

app/views/static_pages/_contentnav.html.erb
<div class="row featurette">
<%= link_to image_tag("navgraphics/engineering_process.png", :alt => "Engineering for Kids: Engineering Process", :class => 'catbutton'), engineering_process_path %>

<%= link_to image_tag("navgraphics/materials.png", :alt => "Engineering for Kids: Materials", :class => 'catbutton'), materials_path %>

<%= link_to image_tag("navgraphics/structures.png", :alt => "Engineering for Kids: Structures", :class => 'catbutton'), structures_path %>

<%= link_to image_tag("navgraphics/machines.png", :alt => "Engineering for Kids: Machines", :class => 'catbutton'), machines_path %>

<%= link_to image_tag("navgraphics/energy.png", :alt => "Engineering for Kids: Energy", :class => 'catbutton'), energy_path %>

<%= link_to image_tag("navgraphics/computing.png", :alt => "Engineering for Kids: Programming", :class => 'catbutton'), computing_path %>
</div>

app/views/static_pages/_resourcesnav.html.erb
<div class="row featurette"  style="padding-top: 10px; padding-bottom: 10px">

	  <!-- <div class ="thumbnail" >  -->
	
		<span class="visible-sm visible-md visible-lg">
			<%= link_to image_tag("navgraphics/web_resources.png", :class => 'catbutton', :class=> 'featurette-image img-responsive center-block', :alt => "Engineering Web Resources"), resources_web_resources_path %>
	
		<br>
			<%= link_to image_tag("navgraphics/toys_and_games.png", :alt => "Engineering Toys and Games", :class => 'catbutton', :class=> 'featurette-image img-responsive center-block'),  resources_toys_and_games_path %>
		<br>
			<%= link_to image_tag("navgraphics/camps_and_events.png", :class => 'catbutton', :alt => "Engineering Related Camps and Events", :class=> 'featurette-image img-responsive center-block'), resources_camps_and_events_path %>
		<br>
			<%= link_to image_tag("navgraphics/scholarships.png",  :class => 'catbutton', :class=> 'featurette-image img-responsive center-block', :alt => "Engineering Scholarships and Awards"), resources_awards_scholarships_path %>
		<br>	
			<%= link_to image_tag("navgraphics/books.png", :class => 'catbutton', :class=> 'featurette-image img-responsive center-block', :alt => "Engineering Books"), resources_books_path %>
		</span>
	  <!-- </div>  -->
	
</div>

app/views/static_pages/intro_to_engineering.html.erb
<% provide(:title, 'Introducing Kids to Engineering: 2025 Labs') %>
<% provide(:description, 'We introduce kids to Engineering and build their technological literacy. We use a lightweight, big-picture overview of Engineering involving a four-part framework: Engineering Process, Machines, Energy, and Computing.') %>

<div class="row">
	<div class="col-sm-2">
		<%= render "contentnav" %>
	</div>

	<div class="col-sm-7">
		<h2>Intro to Engineering</h2>
		We want to get more kids interested in Engineering. (See our <%= link_to "Research",   research_path %> page for motivation on that front.) We think that requires a combination of introducing kids to Engineering and building their technological literacy. We have discovered that figuring out how to build our kids' technological literacy often meant building our own.
		<p></p>

		<a href="http://www.merriam-webster.com/dictionary/engineering" target="_blank">Merriam-Webster</a> defines engineering as the <i>"application of science and mathematics by which the properties of matter and the sources of energy in nature are made useful to people"</i>. A shorthand way of thinking of engineering is that it is application of math and science to make or maintain useful technology.
		<p></p>

		Engineering was not part (and largely is still not) part of the K-12 Curriculum, so if you didn't specialize in Engineering or any other field of study or work related to a particular technology, you might not know how any of this stuff works. The purpose of this area of the web site is to get the adults in the picture comfortable with and conversant in the topics. We know that some find Engineering daunting; we would like to demystify it a bit with a lightweight, big-picture overview of Engineering using a four-part framework. If you do have an Engineering or technical background, you've got a head start, but we think you'll still benefit from this introduction. We're also using this framework to flag the <%= link_to "Resources",   resources_path %> listed on this website, so that you can refer back to this content to know how each resource relates to the world of Engineering.
		<p></p>


		What you will learn in this introductory area of the website:
		<p></p>
		<div class="row">
			<div class="col-sm-1">
				<%= link_to image_tag("pics/eptag.png", :alt => "Engineering Process Icon", :class => "iconleft"), engineering_process_path %>
			</div> <!-- col-sm-1 -->
			
			<div class="col-sm-11">
				<b><%= link_to "Engineering Process",   engineering_process_path %></b> Our framework starts with an explanation of the processes engineers use to turn an idea into technology, or to accomplish other goals found under the umbrella of Engineering.
			</div> <!-- col-sm-11 -->
		</div> <!-- row -->
		</br>

		<div class="row">
			<div class="col-sm-1">
				<%= link_to image_tag("pics/mttag.png", :alt => "Materials Icon", :class => "iconleft"), materials_path %>	
			</div> <!-- span 1 -->
			
			<div class="col-sm-11">
				<b><%= link_to "Materials",  materials_path %></b> You will learn about some history with respect to materials discovery, key properties of materials, selecting materials as part of the engineering design process based on planned functions, and some details about specific materials of interest in our modern era.
			</div> <!-- col-sm-11 -->
		</div> <!-- row -->
		</br>

		<div class="row">
			<div class="col-sm-1">
				<%= link_to image_tag("pics/stag.png", :alt => "Structures Icon", :class => "iconleft"), structures_path %>
			</div> <!-- col-sm-1 -->
			
			<div class="col-sm-11">
				<b><%= link_to "Structures",  structures_path %></b> You will learn about key concepts in the engineering of structures, including the definition of a "structure", forces that act on structures, and key elements such as beams, columns, and arches.
			</div> <!-- col-sm-11 -->
		</div> <!-- row -->
		</br>

		<div class="row">
			<div class="col-sm-1">
				<%= link_to image_tag("pics/mtag.png", :alt => "Machines Icon", :class => "iconleft"), machines_path %>
			</div> <!-- col-sm-1 -->
			
			<div class="col-sm-11">
				<b><%= link_to "Machines",   machines_path %></b> You will learn that machines are one type of technology created by engineers, and you will get an introduction into how machines make work easier.
			</div> <!-- col-sm-11 -->
		</div> <!-- row -->
		</br>
		
		<div class="row">
			<div class="col-sm-1">
				<%= link_to image_tag("pics/entag.png", :alt => "Energy Icon", :class => "iconleft"), energy_path %>
			</div> <!-- col-sm-1 -->
			
			<div class="col-sm-11">
				<b><%= link_to "Energy",   energy_path %></b> Technology doesn't exist or work without energy, so you will learn how we collect and consume the energy that powers the devices in our daily lives.
			</div> <!-- col-sm-11 -->
		</div> <!-- row -->
		</br>

		<div class="row">
			<div class="col-sm-1">
				<%= link_to image_tag("pics/ctag.png", :alt => "Computing Icon", :class => "iconleft"), computing_path %>
			</div> <!-- col-sm-3 -->
		
			<div class="col-sm-11">
				<b><%= link_to "Computing",   computing_path %></b> Since we live in the information age, any study of engineering is incomplete without an overview of computing. In this section you will learn what "computing" means, as well as some very basic knowledge of computer architecture, communications (networking), and the ever-increasing degree to which our lives are supported by computerized automation.
			</div> <!-- col-sm-11 -->
		</div> <!-- row -->
    </div> <!--col-sm-7-->	

	<div class="col-sm-3">	
		<br><br><%= link_to image_tag("facts/sciedu.png", :alt => "Science is taught daily in just 1 in 5 classrooms", :class => "iconleft"), research_path %>
		<hr>
		
		<div class="row">
			<div class="col-sm-12">				
			</div> <!--col-sm-12-->
		</div> <!--row-->

		<div class="row" style="text-align:center">	
			<iframe src="http://rcm-na.amazon-adsystem.com/e/cm?t=2025labs-20&o=1&p=29&l=ur1&category=gift_certificates&banner=14RFZN99KWC9ZBXB4382&f=ifr" width="120" height="600" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
			
			</div> <!--row-->
			
	</div>	<!--col-sm-3-->
</div><!--row-->